### PR TITLE
Godot 4.2 Update

### LINKED ISSUE #8: godot 4
Hi

Can you please make a branch for godot 4?
Godot 4 is in beta and soon will be released.

### PR DESCRIPTION
**Pull request by C-Corgi**
Mostly confident this is working

Couldnt get the light cookie working though
also fixed the .gitignore

Fixes #8

### CODE REVIEW

**Review by tavurth — APPROVED** [review]

**Comment by tavurth** [comment]
LGTM, thank you!

**Comment by tavurth** [comment]
I think I will leave the itch.io demo as 3.x for now however, as in 4.x html-games are really problematic on Mac os

**Comment by tavurth** [comment]
@C-Corgi I see a few issues fixing most of them now:

- The materials from the walls and floor disappeared
- The skybox has gone
- The character has been destroyed
Screenshot 2023-12-04 at 12 08 42

- There were a few warnings which had been added

**Comment by C-Corgi** [comment]
Ah I didn't notice those, I was primarily focused on scripts and getting those working (which they pretty much did out of the box)

**Comment by tavurth** [comment]
Due to these issues I had to revert the merge unfortunately.

It seems that most of the project is working fine after the automatic conversion to 4.x anyway so I'll just fix these broken things from the old master.

**Comment by tavurth** [comment]
@C-Corgi I got all this stuff working again and an improved character model, but I will release a bit later when I've got another project finished:


https://github.com/tavurth/godot-simple-fps-camera/assets/100964/1160c91c-fb9d-486c-8731-b47d14adbc6d

**Pull request merged**
